name: qr_app
description: A new Flutter application.

version: 2.0.0+15

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.6
  url_launcher: ^5.4.1
  share: ^0.6.3+5
  qr_code_scanner: ^0.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

