name: qr_app
description: A new Flutter application.

version: 2.0.3+22

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.8
  url_launcher: ^5.5.0
  share: ^0.6.4+3
  qr_code_scanner: ^0.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

